# Python  Boot Camp 5
This is a continuation of [Python Boot Camp 4](python_boot_camp_4.ipynb). Based on [MATLAB Onramp](https://matlabacademy.mathworks.com)

### Getting Started
Run the code cell below to get started.

In [ ]:
%pylab inline
import random

data=array([[1, 1, 1.2],[1.5, 1, 1.25],[0.5, 1, 1.30],[0.5, 0.5, 1.1],[1, 0.25, 0.92],[0.5, 0.1, 0.64],[3, 3, 1.27],[1, 4, 1.28],[3, 2, 1.25],[4, 1, 1.30],[0.5, 0.25, 0.94],[2, 0.05, 0.41]])
h, m, r = data.T  # this transposes the array data so we can easily extract the columns

## 12. Logical Indexing

Relational operators, such as `>`, `<`, `==`, and `~=` perform comparisons between two values. The outcome of a comparison for equality or inequality is a Boolean variable that has a value of either `True` or `False`.

>**TASK**: Use the relational operator, `<`, to test if `π` is less than `4`. Assign the output to a variable named `test`.

<hr>

We can compare a `numpy` array to a single scalar value using relational operators. The result is a logical array of the same size as the original array:

```
In  [1]: array([5, 10, 15]) > 12
Out [1]: array([False, False,  True])
```

>**TASK**: Test the 1D array `h` for elements that are less than 2. Assign the output to a variable named `test`.

<hr>

We can use a logical array as an array index, which will extract the array elements where the index is true. The following example will extract all elements in `h` that are greater than two:
```
In  [1]: h2 = h[h > 2]
         h2
Out [1]: array([3., 3., 4.])
```

>**TASK**: Create a variable `h1` containing all the elements in `h` that are less than or equal to (`<=`) one.

<hr>

We can also use logical indexing with two different 1D arrays, here we use a condition on `h` to index `r`:

```
In  [1]: r2 = r[h > 2]
         r2
Out [1]: array([1.27, 1.25, 1.3 ])
```

>**TASK**: Create a variable `m_lo` that contains the elements in `m` corresponding to where `r` is less than 1.

<hr>

We can use logical indexing to reassign values in an array. For example, if we wish to replace all values in an array `x` that are equal to 999 with the value 1, we use the following syntax:

```
x[x==999] = 1
```
>**TASK**: Modify `r` so that any value less than 0.5 is replaced with the value 0.

#### Further Practice
We can use the logical operators and (`&`) and or (`|`) to combine logical comparisons. To prioritize the comparisons, we need to put them in parentheses, *e.g.* `(h > 2)`.

To find values less than 2 and greater than 1, use &:
```
x = h[(h<2) & (h>=1)]
```

To find values greater than 2 or less than 1, use |:
```
x = h[(h>2) | (h<1)]
```

Try getting the values in `r` that are between 0.5 and 1.0.

## 12. Programming Constructs

### Decision Branching

The body of an `if` block is only executed if the condition is true:

```
if y == 1:
     print ("This is true")
     y = y + 1
```

Note the colon (`:`) after the boolean condition, and the indented block of commands that follow. When the indentation ends, the `if` block ends.

>**TASK**: Modify the following script so that the plotting code on lines 3-6 are executed only when `doPlot` is 1. *hint: the "equal" operator is `==`.*

In [ ]:
do_plot = random.choice([0, 1])

plot(m, r, 'o')
xlabel('Methylcyclohexane Partial Pressure / atm')
ylabel("Rate / mol kg$_{cat}^{-1}$ s$^{-1}$")
show()

<hr>

Often in these situations, we may want to execute some other code if the condition is not met. To do this, you can use the `else` keyword:
```
x = rand()
if x > 0.5:
    y = 3
else:
    y = 4
y
```
>**TASK**: Modify the plotting script above so that when `do_plot` is not 1, following lines of code are executed:
```
exp=random.choice(range(len(r)))
print(f"The rate of experiment {exp} is {r[exp]} mol/kg/s")
```

#### Further Practice:

The `elif` keyword can be used after `if` to add more conditions. You can include multiple `elif` blocks.

Try adding a variable `do_plot_anyway` to choose whether to make the plot even if `do_plot = False`.. Add this condition with an `elif` block.

### For loops

When the following `for` loop is run, the loop body will be executed three times, as the loop counter `c` progresses through the values `range(3) = [0, 1, 2]`:

```
for c in range(3):
    print(c)
```
Note the colon (`:`) after the `range` function, and the indented block of commands that follow. When the indentation ends, the `for` block ends. 

One cool thing about python loops is that we can loop over any list, and we don't need to know the length.  The following code actually works:

```
pets = ['dog', 'cat', 'fish', 'snake']
for p in pets:
    print(f'My favorite pet is a {p}!')
```

>**TASK**: Wrap the code below in a `for` loop to print out even multiples of `π` up to `8π`

In [ ]:
m=2
print(f'{m} times π equals {m*pi}.')

#### Further Practice

Sometimes we need both the *value* and the *index* of an array element within a `for` loop. For this we can use the `enumerate` function:

```
for ii, p in enumerate(pets):
    print(f'The index of {p} in pets is {ii}')
```

Try printing the index of the even multiples of `π`.

<hr style="height:4px;border-width:0;color:gray;background-color:gray">

This is the end of **Python Boot Camp 5**. Be sure to save by pressing the "S" key in command mode, and continue to [**Python Boot Camp 6**](python_boot_camp_6.ipynb).