# Python Boot Camp 2 Solution
This is a continuation of [Python Boot Camp 1](python_boot_camp_1.ipynb). Based on [MATLAB Onramp](https://matlabacademy.mathworks.com)

### Required  packages
Import `pylab` to get started

In [1]:
from pylab import *

## 3. 1D and 2D Arrays
Create Python variables that contain multiple elements.

### Python Data Types

Python has a number of [built-in data types](https://www.w3schools.com/python/python_datatypes.asp), in the following categories:
 
 - Text Type:	string, abbreviated `str`
 - Numeric Types:	integer `int`, floating point `float`, `complex`
 - Sequence Types:	`list`, `tuple`, `range`
 - Mapping Type:	dictionary `dict`
 
Of these, we will mostly use the `str`, `int`, `float`, and `list` types.  The other types can also be useful though:

 - The `tuple` type is like a list, except it is immutable, meaning it cannot be changed once defined.
 - The `dict` type allows for storage of data consisting of key value pairs, making it a mini database.

### Python lists

In Python, a `list` is a collection of multiple elements, separated by commas and enclosed in square brackets. **Note that, unlike MATLAB, the comma separator is _required_.**

```
In  [1]: p = [3, 'film']
``` 
> **TASK:** Create a list named x with two elements: 7 and 9

In [2]:
x=[7,9]
x

[7, 9]

<hr>

The problem with lists is that we can't do math on them.

> **TASK:** Show that adding 5 to x results in an error.

In [3]:
x + 5

TypeError: can only concatenate list (not "int") to list

<hr>

`numpy` contains a function `array` that converts lists of numbers to a form that we can use to do math.

> **TASK:** Create an array `z` from `x` using `array(x)`

In [4]:
z=array(x)
z

array([7, 9])

<hr>

> **TASK:** add 5 to every element of array z

In [5]:
z = z + 5
z

array([12, 14])

<hr>

> **TASK:** Create an array named x that contains the values 3, 10, and 5 in that order.

In [6]:
x=array([3, 10, 5])
x

array([ 3, 10,  5])

<hr>

We can make a two-dimensional array using a list of lists:

```
In  [1]: x = array( [ [3, 4, 5], [6, 7, 8] ] )
         x
Out [1]: array([[3, 4, 5],
                [6, 7, 8]])
```
> **TASK:** Create a 2D array named x with the values shown below.
```
5    6    7
8    9   10
```

In [7]:
x = array([ [5, 6, 7], [8, 9, 10] ])
x

array([[ 5,  6,  7],
       [ 8,  9, 10]])

<hr>

In Python, we can perform calculations within the square brackets.

```
In  [1]: x = array([abs(-4), 4**2])
         x
Out [1]: array([ 4, 16])
```

**Note:** Python uses a double-asterisk `**` as the symbol for exponents, not the carat `^` as in MATLAB. 

> **TASK:** Create a 1D array named `x` that contains `sqrt(10)` as its first element and $\pi^2$ as its second element.

In [8]:
x = array([sqrt(10), pi**2])
x

array([3.16227766, 9.8696044 ])

### Creating Evenly-Spaced Arrays

It is common to create arrays containing evenly-spaced numbers. For large arrays, entering individual numbers is not practical. An alternative, shorthand way to create evenly-spaced arrays is to use numpy's `arange` function:
```
In  [1]: x = arange(4, 12, 2)
         x
Out [1]: array([ 4,  6,  8, 10])
```

Note that `4` is the starting value, `12` is the first _excluded_ value, and `2` is the step size. This function is the array version of the function `range` that is built into Python.

> **TASK:** Create an array named x with values 1, 2, 3, and 4, using the `arange` function.

In [9]:
x = arange(1,5,1)
x

array([1, 2, 3, 4])

### Creating arrays with `linspace`

If the step size is a non integer, such as 0.1, it is best to use `numpy.linspace`. 

```
In  [1]: y = linspace(0.4,3,6)
         y
Out [1]: array([0.4 , 0.92, 1.44, 1.96, 2.48, 3.  ])
```

Here, `0.4` is the starting value, `3` is the last _included_ value, and `6` is the number of elements in the array. This function is equivalent to the `linspace` function in MATLAB.

> **TASK:** Create an array named x that starts at 1, ends at 10, and contains 5 elements.

In [10]:
linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Array Creation Functions

`numpy` includes functions to create commonly used matrices, such as matrices of random numbers.
```
In  [1]: x = random_sample([2,2])
         x
Out [2]: array([[0.78363163, 0.07238245],
                [0.68659162, 0.17798821]])
```
Note that the inputs to the functon `random_sample` is a list representing the dimensions of the random array.
> **TASK:** Create a variable named x that is a 5-by-4 array of random numbers.

In [11]:
x = x = random_sample([5,4])
x

array([[0.16453763, 0.81420405, 0.57480524, 0.30666953],
       [0.88556351, 0.74947109, 0.00744754, 0.10400907],
       [0.22558488, 0.65504948, 0.12985234, 0.04557496],
       [0.68968706, 0.21217635, 0.11742069, 0.97289115],
       [0.95179428, 0.04066282, 0.17045966, 0.20920108]])

<hr>

> **TASK:** Use the `zeros` function to create an array of all zeros that has 6 rows and 3 columns (6-by-3). Assign the result to a variable named x.

In [12]:
x=np.zeros([6,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<hr>

#### Further Practice:
 - What do you think the function `numpy.ones` does?
 - How do we get the size of an existing array? We can use `numpy.shape`.
 - We can also create an array with the same size as an existing array using `numpy.zeros_like` or `numpy.ones_like`.

## 4. Loading and Saving Data
We don't often save data to files in Python, but we may import data from an external source. Let's load some data from a "comma separated value" or CSV file using `np.loadtxt`. As inputs, this function requires the file name or path as a text string, and we need to specify the `delimiter` between values to be a comma.   
```
In  [1]: data = loadtxt('data.csv', delimiter=',')
``` 
> **TASK:** Load the data in `data.csv` into an array named `data` and show that the `shape` of this array is `(40, 19)`

In [13]:
data = np.loadtxt('data.csv', delimiter=',')
shape(data)

(40, 19)

## 5. Indexing into and Modifying Arrays
Use indexing to extract and modify rows, columns, and elements of `numpy` arrays.

### Indexing into Arrays

We can extract values from an array using row, column indexing.

```
In  [1]: y =  A[5, 7]
``` 

This syntax extracts the value in the 5th row and 7th column of `A` and assigns the result to the variable `y`. A couple of important notes:

 - Indexing into arrays and lists is done using square brackets with comma separators, `[5, 7]`.
 - For a 2D array, the first index is always the row number and the second index the column number, just like MATLAB.
 - **Python indexing starts with 0 (zero) and so the beginning row is the `0th` row and the `5th` row has 5 rows above it!!**

> **TASK:** Create a variable `x` that contains the value in the `0th` row and `3rd` column of the array `data`.

In [14]:
x = data[0,3]
x

29.0

<hr>

You can use the index `-1` as either a row or column index to reference the last element.
```
In  [1]: y = A[-1,2]
``` 

> **TASK:** Use the `-1` index to obtain the value in the last row and 4th column of the array `data`. Assign this value to a variable named x.

In [15]:
x=data[-1,4]
x

13.0

<hr>

We can access elements close to the end of an array using larger negative indices.
```
In  [1]: y =  A[-3,-2]
``` 

> **TASK:** Create a scalar variable `x` that contains the value in the second to last row and 3rd to last column of `data`.

In [16]:
x=data[-2,-3]
x

58.0

<hr>

#### Further Practice
If you only use one index with a 2D array, it will return the row associated with that index. Using one index, try extracting the eighth row of `data`.

You can also use variables as your index. Try creating a variable `y`, and use `y` as the index to `data`.

In [17]:
y = 3
data[y]

array([27.        , 25.        , 16.        , 26.5       , 13.        ,
       23.        ,  6.66666667, 40.        ,  8.225     , 10.        ,
       17.        , 15.5       ,  0.        , 19.        ,  8.58333333,
       10.        , 81.        , 66.        , 18.375     ])

When used as an index, the colon operator (:) specifies all the elements in that dimension. The syntax
 ```
 x = A[2,:]
 ```
creates a 1D array containing all of the elements from the `2nd` row of A. In this case both `A[2]` and `A[2,:]` produce the same result.

> **TASK:** Create a variable named `density` that contains the second column of the 2D array named `data`.

In [18]:
density=data[:,2]
density

array([15. , 14. , 11. , 16. , 18. ,  2. , 15. , 12. ,  0. , 20. ,  5.5,
       17. , 15. ,  0. , 14. ,  0. , 17. , 15. ,  8. , 18. , 19. , 11. ,
       17. , 16. , 15. , 18. , 18. , 20. ,  0. , 16. , 11. , 17. , 19. ,
        0. , 17. , 15. , 11. ,  6. ,  0. , 16. ])

<hr>

The colon operator can refer to a range of values. The following syntax creates a 2D array containing the `0th` through `2nd` columns of the array `A`.

```
y =  A[:, 0:3]
``` 

**Note:** The value `3` represents the first _excluded_ column extracted from `A`. If there is no excluded column (*i.e.* we want to include column `-1`) we can omit an index, for example:
```
y =  A[:, 0:]
``` 

> **TASK:** Create a variable `volume` containing the last two columns of `data`.

In [19]:
volume= data[:,-2:]
volume

array([[ 73.   ,  21.5  ],
       [ 87.   ,  24.125],
       [ 90.   ,  23.375],
       [ 66.   ,  18.375],
       [ 72.   ,  17.125],
       [ 52.   ,  17.75 ],
       [ 79.   ,  20.625],
       [ 54.   ,  14.125],
       [ 60.   ,  18.5  ],
       [ 75.   ,  20.25 ],
       [ 48.   ,  14.125],
       [ 81.   ,  22.   ],
       [ 84.   ,  22.75 ],
       [ 59.   ,  18.5  ],
       [ 77.   ,  20.625],
       [ 81.   ,  17.   ],
       [ 90.   ,  24.625],
       [ 69.   ,  13.5  ],
       [ 80.   ,  21.625],
       [ 70.   ,  18.75 ],
       [ 80.   ,  21.   ],
       [ 87.   ,  22.75 ],
       [102.   ,  23.625],
       [104.   ,  25.5  ],
       [ 86.   ,  23.375],
       [ 98.   ,  26.   ],
       [ 87.   ,  21.75 ],
       [ 92.   ,  24.75 ],
       [ 61.   ,  16.375],
       [ 95.   ,  23.375],
       [ 82.   ,  20.875],
       [101.   ,  25.375],
       [ 91.   ,  23.   ],
       [ 45.   ,  14.125],
       [ 90.   ,  21.875],
       [ 61.   ,  16.   ],
       [ 32.   ,  12.25 ],
 

<hr>

`1D` arrays require a single index. For example: 

```
u =  v[4]
``` 

returns the `4th` element of 1D array `v`.
> **TASK:** Using a single index value, create a variable named `p` containing the `6th` element in the 1D array `density`.

In [20]:
p=density[6]
p

15.0

<hr>

A single range of index values can be used to reference a subset of a 1D array. For example: 

```
x = v[3:]
```

returns a subset of 1D array `v` from the `3rd` element to the end.

> **TASK:** Using a range of index values, create a 1D array named `p` containing the `2nd` through `5th` elements of `density`.

In [21]:
p=density[2:6]
p

array([11., 16., 18.,  2.])

In [22]:
density[[1, 3, 6]]

array([14., 16., 15.])

<hr>

#### Further Practice
Indices can be lists of non-consecutive numbers, such as `[4, 8, 3]` Try extracting the first, third, and sixth elements of density.

Remember we can use the `:` character to extract entire columns of data.
> **TASK:** Create a 1D array named `v1` containing the last column of `data`.

In [23]:
v1=data[:,-1]
v1

array([21.5  , 24.125, 23.375, 18.375, 17.125, 17.75 , 20.625, 14.125,
       18.5  , 20.25 , 14.125, 22.   , 22.75 , 18.5  , 20.625, 17.   ,
       24.625, 13.5  , 21.625, 18.75 , 21.   , 22.75 , 23.625, 25.5  ,
       23.375, 26.   , 21.75 , 24.75 , 16.375, 23.375, 20.875, 25.375,
       23.   , 14.125, 21.875, 16.   , 12.25 , 11.125, 18.25 , 18.875])

### Changing Values in Arrays

<hr>

It's very important to note that `v1` is not independent of `data`. If we change `v1`, we change `data`. We can alter elements of an array by combining indexing with assignment:
```
A[2] = 11
```

> **TASK:** Change the `0th` element in `v1` from 21.5 to 0.5. Then, show that `data[0,-1]` also changes.

In [24]:
v1[0] = 0.5
data[0,-1]

0.5

<hr>

> **TASK:** Change the value of the element in the first row and last column of data back to 21.5. What happens to `v1[0]`?

In [25]:
data[0,-1]=21.5
v1[0]

21.5

<hr>

If we want to make `v1` a separate, independent copy, we can use the `numpy.copy` function.

```
y= copy(A[:,0])
```

> **TASK:** Create a 1D array named `v2` that contains the last column of `data`, by using the `copy` function. Then, change the value of the `0th` element of `v2` to `0.5` and show that `data[0,-1]` remains 21.5.

In [26]:
v2=copy(data[:,-1])
v2[0]=0.5
data[0,-1]

21.5

<hr>

#### Further Practice

We can combine indexing with assignment to change array values to equal other elements. For example, this code would change the value of x[1] to x[2]:
```
x[1] = x[2]
```

Try changing the `0th` column of `data` to the `1st` column of `data`.

In [27]:
r1, r2, r3 = random_sample(3)
r1, r2, r3

(0.5918374431618141, 0.7542978449436479, 0.9106466820902557)

### Unpacking Lists and Arrays

Both lists and arrays can be unpacked into individual variables:

```
k1, k2, k3, k4 = [0.1, 0.2, 0.3, 0.5]
```

> **TASK:** Create a 1D random array of length 3 using `random_sample` and unpack it into three variables, `r1`, `r2`, `r3`

<hr>

We can add together any two arrays of the same size.

```
z = x + y
```

> **TASK:** Create a 1D array `vavg` that is the average of the arrays `v1` and `v2`.

In [28]:
vavg = (v1 + v2) / 2
vavg

array([11.   , 24.125, 23.375, 18.375, 17.125, 17.75 , 20.625, 14.125,
       18.5  , 20.25 , 14.125, 22.   , 22.75 , 18.5  , 20.625, 17.   ,
       24.625, 13.5  , 21.625, 18.75 , 21.   , 22.75 , 23.625, 25.5  ,
       23.375, 26.   , 21.75 , 24.75 , 16.375, 23.375, 20.875, 25.375,
       23.   , 14.125, 21.875, 16.   , 12.25 , 11.125, 18.25 , 18.875])

## 6. Array Calculations
Perform calculations on entire arrays at once.

<hr>

Basic statistical functions in Python can be applied to an array to produce a single output. The maximum value of a 1D array can be determined using the `np.max` function.
```
xMax = max(x)
```
> **TASK:** Create a variable vm containing the maximum of the array `vavg`.

In [29]:
r = v1 + 1
r

array([22.5  , 25.125, 24.375, 19.375, 18.125, 18.75 , 21.625, 15.125,
       19.5  , 21.25 , 15.125, 23.   , 23.75 , 19.5  , 21.625, 18.   ,
       25.625, 14.5  , 22.625, 19.75 , 22.   , 23.75 , 24.625, 26.5  ,
       24.375, 27.   , 22.75 , 25.75 , 17.375, 24.375, 21.875, 26.375,
       24.   , 15.125, 22.875, 17.   , 13.25 , 12.125, 19.25 , 19.875])

<hr>

In `numpy`, the `*` operator performs element-wise array multiplication, as opposed to matrix multiplication. We can use * to multiply two equally sized arrays. 

```
In  [1]: z = array([3, 4]) * array([10, 20])
         z 
Out [1]: 30    80
```
**NOTE:** Using `numpy`, the "dot" operators `.*` and `./` are not required to accomplish element-wise math, as they are in MATLAB.

> **TASK:** Create a variable named `mass` containing the elementwise product of `density` and `vavg`.

In [30]:
vm = max(vavg)
vm

26.0

<hr>

#### Further Practice
We have performed array operations with arrays of the same size and with scalars and arrays.
The concept of [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) enables operation on other compatible sizes. For example, try the following:

```
x = array([[1, 3, 5, 7], [2, 4, 6, 8]]) * array([1,2,3,4])
```

What size is x?

In [31]:
mass= density * vavg
mass

array([165.    , 337.75  , 257.125 , 294.    , 308.25  ,  35.5   ,
       309.375 , 169.5   ,   0.    , 405.    ,  77.6875, 374.    ,
       341.25  ,   0.    , 288.75  ,   0.    , 418.625 , 202.5   ,
       173.    , 337.5   , 399.    , 250.25  , 401.625 , 408.    ,
       350.625 , 468.    , 391.5   , 495.    ,   0.    , 374.    ,
       229.625 , 431.375 , 437.    ,   0.    , 371.875 , 240.    ,
       134.75  ,  66.75  ,   0.    , 302.    ])

In [32]:
x = array([[1, 3, 5, 7], [2, 4, 6, 8]]) * array([1,2,3,4])
shape(x)

(2, 4)